const font = {
  black: 'Montserrat-Black',
  blackItalic: 'Montserrat-BlackItalic',
  bold: 'Montserrat-Bold',
  boldItalic: 'Montserrat-BoldItalic',
  extraBold: 'Montserrat-ExtraBold',
  extraBoldItalic: 'Montserrat-ExtraBoldItalic',
  extraLight: 'Montserrat-ExtraLight',
  extraLightItalic: 'Montserrat-ExtraLightItalic',
  italic: 'Montserrat-Italic',
  light: 'Montserrat-Light',
  lightItalic: 'Montserrat-LightItalic',
  medium: 'Montserrat-Medium',
  mediumItalic: 'Montserrat-MediumItalic',
  regular: 'Montserrat-Regular',
  semiBold: 'Montserrat-SemiBold',
  semiBoldItalic: 'Montserrat-SemiBoldItalic',
  thin: 'Montserrat-Thin',
  thinItalic: 'Montserrat-ThinItalic',
};

const color = {
  primary: '#456277',
  black: '#1E1E1E',
  clientBorder: '#E1E1E1',
  darkGrey: '#676767',
  inputGrey: '#5C5C5C',
  white: '#FFFFFF',
  grey: '#C2C2C2',
  shadow: '#0078FD',
  overGrey: '#999999',
  lightBlack: '#494949',
  borderGrey: '#D4D4D4',
  Black_shadow: '#000000',
  TextGrey: '#8D8D8D',
  LightBlue: '#3893F8',
  checkBox: '#A3A3A3',
  bottomWidth: '#B3B3B3',
  switchOff: '#CBDEED',
  switchOn: '#00C614',
  distanceTxt: '#4E4E4E',
  valueText: '#121212',
  toggleOffColor: '#CBDEED',
  rightArrow: '#7A7A7A',
  topBorder: '#6C6C6C',
  agreeText: '#8C959C',
  dropdownColor: '#898989',
  searchColor: '#DBDBDB',
  backgroundColor: '#007BFD33',
  red: '#DC0000',
  backgroundColorGiftCard: '#EFEFEF',
  buttonInActive: '#D9D9D9',
};

const theme = {font, color};

export default theme;
